"""Translate untranslated items in items.json.
Rules:
- Game-specific names stay in original form (Ender Pearl, Blaze, TNT, Nether, Wither, etc.)
- Generic item types get translated (sword → Kard, bucket → Vödör, etc.)
- Material names get translated where they are generic material tiers
- Minecraft vanilla item names are kept as-is in English, translated to HU
"""
import json

# Material HU/EN mappings (these ARE translated)
MAT_HU = {
    'adamantium': 'Adamantium',
    'ancient_metal': 'Ősi Fém',
    'copper': 'Réz',
    'silver': 'Ezüst',
    'gold': 'Arany',
    'iron': 'Vas',
    'mithril': 'Mithril',
    'hard_stone': 'Keménykő',
    'hardstone': 'Keménykő',
    'rusted_iron': 'Rozsdás Vas',
    'obsidian': 'Obszidián',
    'bronze': 'Bronz',
    'silver_copper': 'Ezüst-Réz',
    'high_carbon_steel': 'Magas Szén Acél',
    'flint': 'Kova',
    'quartz': 'Kvarc',
    'oak': 'Tölgy',
    'birch': 'Nyír',
    'spruce': 'Fenyő',
    'jungle': 'Dzsungel',
}
MAT_EN = {
    'adamantium': 'Adamantium',
    'ancient_metal': 'Ancient Metal',
    'copper': 'Copper',
    'silver': 'Silver',
    'gold': 'Gold',
    'iron': 'Iron',
    'mithril': 'Mithril',
    'hard_stone': 'Hardstone',
    'hardstone': 'Hardstone',
    'rusted_iron': 'Rusted Iron',
    'obsidian': 'Obsidian',
    'bronze': 'Bronze',
    'silver_copper': 'Silver-Copper',
    'high_carbon_steel': 'High Carbon Steel',
    'flint': 'Flint',
    'quartz': 'Quartz',
    'oak': 'Oak',
    'birch': 'Birch',
    'spruce': 'Spruce',
    'jungle': 'Jungle',
}

# Item type HU/EN (generic types)
TYPE_HU = {
    'anvil': 'Üllő',
    'block': 'Blokk',
    'bucket': 'Vödör',
    'bucket_filled_with_milk': 'Tejes Vödör',
    'bucket_filled_with_stone': 'Kőzetes Vödör',
    'bucket_filled_with_water': 'Vizes Vödör',
    'bucket_of_milk': 'Tejes Vödör',
    'bucket_of_stone': 'Kőzetes Vödör',
    'bucket_of_water': 'Vizes Vödör',
    'chain_boots': 'Lánc Csizma',
    'chain_chestplate': 'Lánc Mellvért',
    'chain_helmet': 'Lánc Sisak',
    'chain_leggings': 'Lánc Lábvért',
    'coin': 'Érme',
    'door': 'Ajtó',
    'fence': 'Kerítés',
    'fence_gate': 'Kerítés Kapu',
    'flint_and_steel': 'Tűzkő és Acél',
    'fluid_tank': 'Folyadék Tank',
    'hand_axe': 'Kézifejsze',
    'ore': 'Érc',
    'shield': 'Pajzs',
    'short_sword': 'Rövid Kard',
    'shovel': 'Ásó',
    'war_hammer': 'Háborús Kalapács',
    'bow': 'Íj',
    'nugget': 'Ércdarab',
    'pickaxe': 'Csákány',
    'axe': 'Fejsze',
    'sword': 'Kard',
    'battle_axe': 'Csatafejsze',
    'boots': 'Csizma',
    'chestplate': 'Mellvért',
    'helmet': 'Sisak',
    'leggings': 'Lábvért',
    'dagger': 'Tőr',
    'hoe': 'Kapa',
    'mattock': 'Kapacs',
    'scythe': 'Kasza',
    'shears': 'Olló',
    'knowledge_book': 'Tudáskönyv',
    'barrel_upgrade': 'Hordó Fejlesztés',
    'chest_upgrade': 'Láda Fejlesztés',
    'filter_paper': 'Szűrőpapír',
    'sieve': 'Szita',
    'wood_crate': 'Fa Láda',
    'wood_slab_single': 'Fa Félblokk',
    'wood_stairs': 'Fa Lépcső',
    'slab_single': 'Félblokk',
    'stairs': 'Lépcső',
    'wall': 'Fal',
    'leaves': 'Levelek',
}
TYPE_EN = {
    'anvil': 'Anvil',
    'block': 'Block',
    'bucket': 'Bucket',
    'bucket_filled_with_milk': 'Bucket of Milk',
    'bucket_filled_with_stone': 'Bucket of Stone',
    'bucket_filled_with_water': 'Bucket of Water',
    'bucket_of_milk': 'Bucket of Milk',
    'bucket_of_stone': 'Bucket of Stone',
    'bucket_of_water': 'Bucket of Water',
    'chain_boots': 'Chain Boots',
    'chain_chestplate': 'Chain Chestplate',
    'chain_helmet': 'Chain Helmet',
    'chain_leggings': 'Chain Leggings',
    'coin': 'Coin',
    'door': 'Door',
    'fence': 'Fence',
    'fence_gate': 'Fence Gate',
    'flint_and_steel': 'Flint and Steel',
    'fluid_tank': 'Fluid Tank',
    'hand_axe': 'Hand Axe',
    'ore': 'Ore',
    'shield': 'Shield',
    'short_sword': 'Short Sword',
    'shovel': 'Shovel',
    'war_hammer': 'War Hammer',
    'bow': 'Bow',
    'nugget': 'Nugget',
    'pickaxe': 'Pickaxe',
    'axe': 'Axe',
    'sword': 'Sword',
    'battle_axe': 'Battle Axe',
    'boots': 'Boots',
    'chestplate': 'Chestplate',
    'helmet': 'Helmet',
    'leggings': 'Leggings',
    'dagger': 'Dagger',
    'hoe': 'Hoe',
    'mattock': 'Mattock',
    'scythe': 'Scythe',
    'shears': 'Shears',
    'knowledge_book': 'Knowledge Book',
    'barrel_upgrade': 'Barrel Upgrade',
    'chest_upgrade': 'Chest Upgrade',
    'filter_paper': 'Filter Paper',
    'sieve': 'Sieve',
    'wood_crate': 'Wood Crate',
    'wood_slab_single': 'Wood Slab',
    'wood_stairs': 'Wood Stairs',
    'slab_single': 'Slab',
    'stairs': 'Stairs',
    'wall': 'Wall',
    'leaves': 'Leaves',
}

# Manual translations
# Note: game-specific names kept as-is in EN; HU uses Hungarian where natural
MANUAL = {
    'advanced_enchantment_table': ('Haladó Bűvölőasztal', 'Advanced Enchantment Table'),
    'advanced_enchantment_table_knowledge_book': ('Haladó Bűvölőasztal Tudáskönyv', 'Advanced Enchantment Table Knowledge Book'),
    'ancient_metal_container_knowledge_book': ('Ősi Fém Konténer Tudáskönyv', 'Ancient Metal Container Knowledge Book'),
    'ancient_metal_filter_paper_knowledge_book': ('Ősi Fém Szűrőpapír Tudáskönyv', 'Ancient Metal Filter Paper Knowledge Book'),
    'ancient_metal_bow': ('Ősi Fém Íj', 'Ancient Metal Bow'),
    'andesite': ('Andezit', 'Andesite'),
    'apple': ('Alma', 'Apple'),
    'armor_stand': ('Páncélállvány', 'Armor Stand'),
    'baked_potato': ('Sült Krumpli', 'Baked Potato'),
    'bamboo': ('Bambusz', 'Bamboo'),
    'banana_leaves': ('Banánfa Levelek', 'Banana Leaves'),
    'barrel': ('Hordó', 'Barrel'),
    'battery_knowledge_book': ('Akkumulátor Tudáskönyv', 'Battery Knowledge Book'),
    'bed_black': ('Fekete Ágy', 'Black Bed'),
    'bed_white': ('Fehér Ágy', 'White Bed'),
    'beef_soup': ('Marhahúsleves', 'Beef Soup'),
    'belt': ('Öv', 'Belt'),
    'binding_scroll': ('Kötő Tekercs', 'Binding Scroll'),
    'birch_door': ('Nyír Ajtó', 'Birch Door'),
    'birch_fence': ('Nyír Kerítés', 'Birch Fence'),
    'birch_fence_gate': ('Nyír Kerítés Kapu', 'Birch Fence Gate'),
    'birch_leaves': ('Nyír Levelek', 'Birch Leaves'),
    'birch_sieve': ('Nyír Szita', 'Birch Sieve'),
    'birch_wood_crate': ('Nyír Fa Láda', 'Birch Wood Crate'),
    'birch_wood_slab_single': ('Nyír Fa Félblokk', 'Birch Wood Slab'),
    'birch_wood_stairs': ('Nyír Fa Lépcső', 'Birch Wood Stairs'),
    'black_carpet': ('Fekete Szőnyeg', 'Black Carpet'),
    'black_stained_clay_colored': ('Fekete Festett Agyag', 'Black Stained Clay'),
    'black_wool': ('Fekete Gyapjú', 'Black Wool'),
    'blue_bed': ('Kék Ágy', 'Blue Bed'),
    'blue_carpet': ('Kék Szőnyeg', 'Blue Carpet'),
    'blue_compass': ('Kék Iránytű', 'Blue Compass'),
    'blue_stained_clay_colored': ('Kék Festett Agyag', 'Blue Stained Clay'),
    'blue_wool': ('Kék Gyapjú', 'Blue Wool'),
    'blueberries': ('Áfonya', 'Blueberries'),
    'blueberry_porridge': ('Áfonya Kása', 'Blueberry Porridge'),
    'boat': ('Csónak', 'Boat'),
    'bone': ('Csont', 'Bone'),
    'bone_club': ('Csontbuzogány', 'Bone Club'),
    'bone_meal': ('Csontliszt', 'Bone Meal'),
    'book_and_quill': ('Könyv és Toll', 'Book and Quill'),
    'bookshelf': ('Könyvespolc', 'Bookshelf'),
    'bottle_o_enchanting': ('Tapasztalat Palack', 'Bottle o\' Enchanting'),
    'bottle_of_disenchanting': ('Varázstalanítás Palack', 'Bottle of Disenchanting'),
    'bowl_milk': ('Tej Tál', 'Bowl of Milk'),
    'bowl_water': ('Vizes Tál', 'Bowl of Water'),
    'brewing_stand': ('Főzőállvány', 'Brewing Stand'),
    'brick_slab_single': ('Tégla Félblokk', 'Brick Slab'),
    'brick_stairs': ('Tégla Lépcső', 'Brick Stairs'),
    'bricks': ('Téglák', 'Bricks'),
    'bronze_war_hammer': ('Bronz Háborús Kalapács', 'Bronze War Hammer'),
    'brown_bed': ('Barna Ágy', 'Brown Bed'),
    'brown_carpet': ('Barna Szőnyeg', 'Brown Carpet'),
    'brown_stained_clay_colored': ('Barna Festett Agyag', 'Brown Stained Clay'),
    'brown_wool': ('Barna Gyapjú', 'Brown Wool'),
    'button_stone': ('Kő Gomb', 'Stone Button'),
    'button_wood': ('Fa Gomb', 'Wood Button'),
    'cactus_green': ('Kaktuszzöld Festék', 'Cactus Green Dye'),
    'cake': ('Torta', 'Cake'),
    'campfire_idle': ('Tábortűz', 'Campfire'),
    'carbon_crystal': ('Szén Kristály', 'Carbon Crystal'),
    'carpet': ('Szőnyeg', 'Carpet'),
    'carrot': ('Sárgarépa', 'Carrot'),
    'carrot_on_a_stick_adamantium': ('Sárgarépa Pálcán (Adamantium)', 'Carrot on a Stick (Adamantium)'),
    'carrot_on_a_stick_ancient_metal': ('Sárgarépa Pálcán (Ősi Fém)', 'Carrot on a Stick (Ancient Metal)'),
    'carrot_on_a_stick_copper': ('Sárgarépa Pálcán (Réz)', 'Carrot on a Stick (Copper)'),
    'carrot_on_a_stick_flint': ('Sárgarépa Pálcán (Kova)', 'Carrot on a Stick (Flint)'),
    'carrot_on_a_stick_gold': ('Sárgarépa Pálcán (Arany)', 'Carrot on a Stick (Gold)'),
    'carrot_on_a_stick_iron': ('Sárgarépa Pálcán (Vas)', 'Carrot on a Stick (Iron)'),
    'carrot_on_a_stick_mithril': ('Sárgarépa Pálcán (Mithril)', 'Carrot on a Stick (Mithril)'),
    'carrot_on_a_stick_obsidian': ('Sárgarépa Pálcán (Obszidián)', 'Carrot on a Stick (Obsidian)'),
    'carrot_on_a_stick_silver': ('Sárgarépa Pálcán (Ezüst)', 'Carrot on a Stick (Silver)'),
    'cauldron': ('Üst', 'Cauldron'),
    'cheese': ('Sajt', 'Cheese'),
    'chest': ('Láda', 'Chest'),
    'chicken_soup': ('Csirkeleves', 'Chicken Soup'),
    'chiseled_quartz_block': ('Faragott Kvarc Blokk', 'Chiseled Quartz Block'),
    'chiseled_sandstone': ('Faragott Homokkő', 'Chiseled Sandstone'),
    'chocolate': ('Csokoládé', 'Chocolate'),
    'clay_furnace_idle': ('Agyag Kemence', 'Clay Furnace'),
    'clay_portal_stone': ('Agyag Portálkő', 'Clay Portal Stone'),
    'clock': ('Óra', 'Clock'),
    'clock_knowledge_book': ('Óra Tudáskönyv', 'Clock Knowledge Book'),
    'coal_block': ('Szén Blokk', 'Coal Block'),
    'coarse_dirt': ('Durva Föld', 'Coarse Dirt'),
    'cobblestone_slab_single': ('Kőlap Félblokk', 'Cobblestone Slab'),
    'cobblestone_wall': ('Kőlap Fal', 'Cobblestone Wall'),
    'cocoa_beans': ('Kakaóbab', 'Cocoa Beans'),
    'coconut_leaves': ('Kókuszpálma Levelek', 'Coconut Leaves'),
    'compass': ('Iránytű', 'Compass'),
    'cooked_beef': ('Sült Marhahús', 'Cooked Beef'),
    'cooked_chicken': ('Sült Csirke', 'Cooked Chicken'),
    'cookie': ('Süti', 'Cookie'),
    'coolant_knowledge_book': ('Hűtőfolyadék Tudáskönyv', 'Coolant Knowledge Book'),
    'core_breaker': ('Kemencemag Törő', 'Core Breaker'),
    'core_breaker_knowledge_book': ('Kemencemag Törő Tudáskönyv', 'Core Breaker Knowledge Book'),
    'cornflower': ('Búzavirág', 'Cornflower'),
    'cream_of_mushroom_soup': ('Gomba Krémleves', 'Cream of Mushroom Soup'),
    'cream_of_vegetable_soup': ('Zöldség Krémleves', 'Cream of Vegetable Soup'),
    'cyan_bed': ('Cián Ágy', 'Cyan Bed'),
    'cyan_carpet': ('Cián Szőnyeg', 'Cyan Carpet'),
    'cyan_dye': ('Cián Festék', 'Cyan Dye'),
    'cyan_stained_clay_colored': ('Cián Festett Agyag', 'Cyan Stained Clay'),
    'cyan_wool': ('Cián Gyapjú', 'Cyan Wool'),
    'dahlia': ('Dália', 'Dahlia'),
    'daisy': ('Százszorszép', 'Daisy'),
    'dandelion': ('Pitypang', 'Dandelion'),
    'dandelion_yellow': ('Pitypangsárga Festék', 'Dandelion Yellow Dye'),
    'daylight_sensor': ('Napfény Érzékelő', 'Daylight Sensor'),
    'diamond_block': ('Gyémánt Blokk', 'Diamond Block'),
    'diamond_shard': ('Gyémánt Szilánk', 'Diamond Shard'),
    'diorite': ('Diorit', 'Diorite'),
    'dirt_portal_stone': ('Föld Portálkő', 'Dirt Portal Stone'),
    'dispenser': ('Adagoló', 'Dispenser'),
    'dough': ('Tészta', 'Dough'),
    'dropper': ('Ejtő', 'Dropper'),
    'egg': ('Tojás', 'Egg'),
    'element_obsidian': ('Elemi Obszidián', 'Elemental Obsidian'),
    'elemental_water_skin_knowledge_book': ('Elemi Víztömlő Tudáskönyv', 'Elemental Water Skin Knowledge Book'),
    'emerald_block': ('Smaragd Blokk', 'Emerald Block'),
    'emerald_shard': ('Smaragd Szilánk', 'Emerald Shard'),
    'empty_antique_atlas': ('Üres Antik Atlasz', 'Empty Antique Atlas'),
    'empty_large_water_skin': ('Üres Nagy Víztömlő', 'Empty Large Water Skin'),
    'empty_map': ('Üres Térkép', 'Empty Map'),
    'empty_water_skin': ('Üres Víztömlő', 'Empty Water Skin'),
    'enchantment_table_emerald': ('Smaragd Bűvölőasztal', 'Emerald Enchantment Table'),
    'ender_chest': ('Ender Láda', 'Ender Chest'),
    'ender_pearl': ('Ender Gyöngy', 'Ender Pearl'),
    'fence': ('Kerítés', 'Fence'),
    'fence_gate': ('Kerítés Kapu', 'Fence Gate'),
    'fire_charge': ('Tűzgolyó', 'Fire Charge'),
    'fish_ball': ('Halgombóc', 'Fish Ball'),
    'fishing_rod_adamantium': ('Adamantium Horgászbot', 'Adamantium Fishing Rod'),
    'fishing_rod_ancient_metal': ('Ősi Fém Horgászbot', 'Ancient Metal Fishing Rod'),
    'fishing_rod_copper': ('Réz Horgászbot', 'Copper Fishing Rod'),
    'fishing_rod_flint': ('Kova Horgászbot', 'Flint Fishing Rod'),
    'fishing_rod_gold': ('Arany Horgászbot', 'Gold Fishing Rod'),
    'fishing_rod_hard': ('Keménykő Horgászbot', 'Hardstone Fishing Rod'),
    'fishing_rod_iron': ('Vas Horgászbot', 'Iron Fishing Rod'),
    'fishing_rod_mithril': ('Mithril Horgászbot', 'Mithril Fishing Rod'),
    'fishing_rod_obsidian': ('Obszidián Horgászbot', 'Obsidian Fishing Rod'),
    'fishing_rod_silver': ('Ezüst Horgászbot', 'Silver Fishing Rod'),
    'flint_and_steel': ('Tűzkő és Acél', 'Flint and Steel'),
    'flint_axe': ('Kova Fejsze', 'Flint Axe'),
    'flint_hatchet': ('Kova Balta', 'Flint Hatchet'),
    'flint_pickaxe': ('Kova Csákány', 'Flint Pickaxe'),
    'flint_shovel': ('Kova Ásó', 'Flint Shovel'),
    'flour': ('Liszt', 'Flour'),
    'flower_pot': ('Virágcserép', 'Flower Pot'),
    'fruit_sorbet': ('Gyümölcs Sorbet', 'Fruit Sorbet'),
    'giant_tnt_knowledge_book': ('Óriás TNT Tudáskönyv', 'Giant TNT Knowledge Book'),
    'glass': ('Üveg', 'Glass'),
    'glass_bottle': ('Üveg Palack', 'Glass Bottle'),
    'glass_pane': ('Üveg Ablak', 'Glass Pane'),
    'glass_shard': ('Üveg Szilánk', 'Glass Shard'),
    'glowstone_torch': ('Izzókő Fáklya', 'Glowstone Torch'),
    'gold_filter_paper': ('Arany Szűrőpapír', 'Gold Filter Paper'),
    'granite': ('Gránit', 'Granite'),
    'gray_bed': ('Szürke Ágy', 'Gray Bed'),
    'gray_carpet': ('Szürke Szőnyeg', 'Gray Carpet'),
    'gray_dye': ('Szürke Festék', 'Gray Dye'),
    'gray_stained_clay_colored': ('Szürke Festett Agyag', 'Gray Stained Clay'),
    'gray_wool': ('Szürke Gyapjú', 'Gray Wool'),
    'green_bed': ('Zöld Ágy', 'Green Bed'),
    'green_carpet': ('Zöld Szőnyeg', 'Green Carpet'),
    'green_stained_clay_colored': ('Zöld Festett Agyag', 'Green Stained Clay'),
    'green_wool': ('Zöld Gyapjú', 'Green Wool'),
    'grindstone': ('Köszörűkő', 'Grindstone'),
    'hard_stone_anvil': ('Keménykő Üllő', 'Hardstone Anvil'),
    'hard_stone_axe': ('Keménykő Fejsze', 'Hardstone Axe'),
    'hard_stone_battle_axe': ('Keménykő Csatafejsze', 'Hardstone Battle Axe'),
    'hard_stone_boots': ('Keménykő Csizma', 'Hardstone Boots'),
    'hard_stone_bucket_of_milk': ('Keménykő Tejes Vödör', 'Hardstone Bucket of Milk'),
    'hard_stone_bucket_of_stone': ('Keménykő Kőzetes Vödör', 'Hardstone Bucket of Stone'),
    'hard_stone_bucket_of_water': ('Keménykő Vizes Vödör', 'Hardstone Bucket of Water'),
    'hard_stone_chestplate': ('Keménykő Mellvért', 'Hardstone Chestplate'),
    'hard_stone_dagger': ('Keménykő Tőr', 'Hardstone Dagger'),
    'hard_stone_flint_and_steel': ('Keménykő Tűzkő és Acél', 'Hardstone Flint and Steel'),
    'hard_stone_fluid_tank': ('Keménykő Folyadék Tank', 'Hardstone Fluid Tank'),
    'hard_stone_hand_axe': ('Keménykő Kézifejsze', 'Hardstone Hand Axe'),
    'hard_stone_helmet': ('Keménykő Sisak', 'Hardstone Helmet'),
    'hard_stone_hoe': ('Keménykő Kapa', 'Hardstone Hoe'),
    'hard_stone_leggings': ('Keménykő Lábvért', 'Hardstone Leggings'),
    'hard_stone_mattock': ('Keménykő Kapacs', 'Hardstone Mattock'),
    'hard_stone_pickaxe': ('Keménykő Csákány', 'Hardstone Pickaxe'),
    'hard_stone_scythe': ('Keménykő Kasza', 'Hardstone Scythe'),
    'hard_stone_shears': ('Keménykő Olló', 'Hardstone Shears'),
    'hard_stone_shield': ('Keménykő Pajzs', 'Hardstone Shield'),
    'hard_stone_shovel': ('Keménykő Ásó', 'Hardstone Shovel'),
    'hard_stone_sword': ('Keménykő Kard', 'Hardstone Sword'),
    'hard_stone_war_hammer': ('Keménykő Háborús Kalapács', 'Hardstone War Hammer'),
    'hardstone_block': ('Keménykő Blokk', 'Hardstone Block'),
    'hardstone_bucket': ('Keménykő Vödör', 'Hardstone Bucket'),
    'hardstone_coin': ('Keménykő Érme', 'Hardstone Coin'),
    'hardstone_nugget': ('Keménykő Ércdarab', 'Hardstone Nugget'),
    'hardstone_ore': ('Keménykő Érc', 'Hardstone Ore'),
    'hay_bale': ('Szénabála', 'Hay Bale'),
    'high_carbon_steel_war_hammer': ('Magas Szén Acél Háborús Kalapács', 'High Carbon Steel War Hammer'),
    'hopper': ('Tölcsér', 'Hopper'),
    'ice_cream': ('Fagylalt', 'Ice Cream'),
    'ice_cream_cone': ('Fagylalt Tölcsér', 'Ice Cream Cone'),
    'ink_sac': ('Tintazacskó', 'Ink Sac'),
    'iron_anvil': ('Vas Üllő', 'Iron Anvil'),
    'iron_bars': ('Vas Rács', 'Iron Bars'),
    'iron_block': ('Vas Blokk', 'Iron Block'),
    'iron_boat': ('Vas Csónak', 'Iron Boat'),
    'iron_bucket': ('Vas Vödör', 'Iron Bucket'),
    'iron_bucket_filled_with_milk': ('Vas Tejes Vödör', 'Iron Bucket of Milk'),
    'iron_bucket_filled_with_stone': ('Vas Kőzetes Vödör', 'Iron Bucket of Stone'),
    'iron_bucket_filled_with_water': ('Vas Vizes Vödör', 'Iron Bucket of Water'),
    'iron_chain_boots': ('Vas Lánc Csizma', 'Iron Chain Boots'),
    'iron_chain_chestplate': ('Vas Lánc Mellvért', 'Iron Chain Chestplate'),
    'iron_chain_helmet': ('Vas Lánc Sisak', 'Iron Chain Helmet'),
    'iron_chain_leggings': ('Vas Lánc Lábvért', 'Iron Chain Leggings'),
    'iron_door': ('Vas Ajtó', 'Iron Door'),
    'iron_fluid_tank': ('Vas Folyadék Tank', 'Iron Fluid Tank'),
    'iron_hand_axe': ('Vas Kézifejsze', 'Iron Hand Axe'),
    'iron_ore': ('Vas Érc', 'Iron Ore'),
    'iron_shield': ('Vas Pajzs', 'Iron Shield'),
    'iron_short_sword': ('Vas Rövid Kard', 'Iron Short Sword'),
    'item_frame': ('Tárgy Keret', 'Item Frame'),
    'jack_o_lantern': ("Jack-o'-Lantern", "Jack-o'-Lantern"),
    'jukebox': ('Zenebox', 'Jukebox'),
    'jungle_door': ('Dzsungel Ajtó', 'Jungle Door'),
    'jungle_fence': ('Dzsungel Kerítés', 'Jungle Fence'),
    'jungle_fence_gate': ('Dzsungel Kerítés Kapu', 'Jungle Fence Gate'),
    'jungle_leaves': ('Dzsungel Levelek', 'Jungle Leaves'),
    'jungle_sieve': ('Dzsungel Szita', 'Jungle Sieve'),
    'jungle_wood_crate': ('Dzsungel Fa Láda', 'Jungle Wood Crate'),
    'jungle_wood_slab_single': ('Dzsungel Fa Félblokk', 'Jungle Wood Slab'),
    'jungle_wood_stairs': ('Dzsungel Fa Lépcső', 'Jungle Wood Stairs'),
    'ladder': ('Létra', 'Ladder'),
    'lantern': ('Lámpa', 'Lantern'),
    'lapis_block': ('Lazúrkő Blokk', 'Lapis Lazuli Block'),
    'lapis_lazuli': ('Lazúrkő', 'Lapis Lazuli'),
    'large_backpack_upgrade': ('Nagy Hátizsák Fejlesztés', 'Large Backpack Upgrade'),
    'latiao': ('Latiao (Csípős Snack)', 'Latiao (Spicy Snack)'),
    'lead': ('Póráz', 'Lead'),
    'leaf_portal_stone': ('Levél Portálkő', 'Leaf Portal Stone'),
    'leather_boots': ('Bőr Csizma', 'Leather Boots'),
    'leather_cap': ('Bőr Sapka', 'Leather Cap'),
    'leather_pants': ('Bőr Nadrág', 'Leather Pants'),
    'leather_sieve_mesh': ('Bőr Szita Háló', 'Leather Sieve Mesh'),
    'leather_tunic': ('Bőr Mellény', 'Leather Tunic'),
    'lever': ('Kar', 'Lever'),
    'light_blue_bed': ('Világoskék Ágy', 'Light Blue Bed'),
    'light_blue_carpet': ('Világoskék Szőnyeg', 'Light Blue Carpet'),
    'light_blue_dye': ('Világoskék Festék', 'Light Blue Dye'),
    'light_blue_stained_clay_colored': ('Világoskék Festett Agyag', 'Light Blue Stained Clay'),
    'light_blue_wool': ('Világoskék Gyapjú', 'Light Blue Wool'),
    'light_gray_bed': ('Világosszürke Ágy', 'Light Gray Bed'),
    'light_gray_carpet': ('Világosszürke Szőnyeg', 'Light Gray Carpet'),
    'light_gray_dye': ('Világosszürke Festék', 'Light Gray Dye'),
    'light_gray_stained_clay_colored': ('Világosszürke Festett Agyag', 'Light Gray Stained Clay'),
    'light_gray_wool': ('Világosszürke Gyapjú', 'Light Gray Wool'),
    'lily_pad': ('Vízililiom Levél', 'Lily Pad'),
    'lime_bed': ('Zöldessárga Ágy', 'Lime Bed'),
    'lime_carpet': ('Zöldessárga Szőnyeg', 'Lime Carpet'),
    'lime_dye': ('Zöldessárga Festék', 'Lime Dye'),
    'lime_stained_clay_colored': ('Zöldessárga Festett Agyag', 'Lime Stained Clay'),
    'lime_wool': ('Zöldessárga Gyapjú', 'Lime Wool'),
    'log_portal_stone': ('Fa Portálkő', 'Log Portal Stone'),
    'lotus_seed_soup': ('Lótusmag Leves', 'Lotus Seed Soup'),
    'magenta_bed': ('Magenta Ágy', 'Magenta Bed'),
    'magenta_carpet': ('Magenta Szőnyeg', 'Magenta Carpet'),
    'magenta_dye': ('Magenta Festék', 'Magenta Dye'),
    'magenta_stained_clay_colored': ('Magenta Festett Agyag', 'Magenta Stained Clay'),
    'magenta_wool': ('Magenta Gyapjú', 'Magenta Wool'),
    'magma_block': ('Magma Blokk', 'Magma Block'),
    'map': ('Térkép', 'Map'),
    'mashed_potato': ('Krumplipüré', 'Mashed Potato'),
    'melon_seeds': ('Görögdinnye Mag', 'Melon Seeds'),
    'mercury_ingot': ('Higany Rúd', 'Mercury Ingot'),
    'mercury_nugget': ('Higany Ércdarab', 'Mercury Nugget'),
    'mercury_ore': ('Higany Érc', 'Mercury Ore'),
    'minecart': ('Minecart', 'Minecart'),
    'minecart_with_chest': ('Minecart Ládával', 'Minecart with Chest'),
    'minecart_with_furnace': ('Minecart Kemencével', 'Minecart with Furnace'),
    'minecart_with_hopper': ('Minecart Tölcsérrel', 'Minecart with Hopper'),
    'minecart_with_tnt': ('Minecart TNT-vel', 'Minecart with TNT'),
    'miner_s_helmet': ('Bányász Sisak', "Miner's Helmet"),
    'miner_s_helmet_knowledge_book': ('Bányász Sisak Tudáskönyv', "Miner's Helmet Knowledge Book"),
    'mint_leaf': ('Borsmenta Levél', 'Mint Leaf'),
    'mint_salad': ('Borsmenta Saláta', 'Mint Salad'),
    'mithril_bow': ('Mithril Íj', 'Mithril Bow'),
    'mossy_cobblestone': ('Mohás Kőlap', 'Mossy Cobblestone'),
    'mossy_cobblestone_portal_stone': ('Mohás Kőlap Portálkő', 'Mossy Cobblestone Portal Stone'),
    'mossy_cobblestone_wall': ('Mohás Kőlap Fal', 'Mossy Cobblestone Wall'),
    'mushroom_brown': ('Barna Gomba', 'Brown Mushroom'),
    'mushroom_red': ('Piros Gomba', 'Red Mushroom'),
    'mushroom_stew': ('Gombás Ragu', 'Mushroom Stew'),
    'nether_brick_fence': ('Nether Tégla Kerítés', 'Nether Brick Fence'),
    'nether_brick_slab_single': ('Nether Tégla Félblokk', 'Nether Brick Slab'),
    'nether_brick_stairs': ('Nether Tégla Lépcső', 'Nether Brick Stairs'),
    'nether_furnace_core': ('Pokoli Kő Kemence Mag', 'Netherrack Furnace Core'),
    'nether_quartz': ('Nether Kvarc', 'Nether Quartz'),
    'netherrack_furnace_idle': ('Pokoli Kő Kemence', 'Netherrack Furnace'),
    'note_block': ('Zenélő Blokk', 'Note Block'),
    'oak_leaves': ('Tölgy Levelek', 'Oak Leaves'),
    'oak_sieve': ('Tölgy Szita', 'Oak Sieve'),
    'oak_wood_crate': ('Tölgy Fa Láda', 'Oak Wood Crate'),
    'oak_wood_slab_single': ('Tölgy Fa Félblokk', 'Oak Wood Slab'),
    'oak_wood_stairs': ('Tölgy Fa Lépcső', 'Oak Wood Stairs'),
    'oatmeal_porridge': ('Zabkása', 'Oatmeal Porridge'),
    'obsidian_axe': ('Obszidián Fejsze', 'Obsidian Axe'),
    'obsidian_furnace_core': ('Obszidián Kemence Mag', 'Obsidian Furnace Core'),
    'obsidian_furnace_idle': ('Obszidián Kemence', 'Obsidian Furnace'),
    'obsidian_hatchet': ('Obszidián Balta', 'Obsidian Hatchet'),
    'obsidian_ingot_mold_cooling': ('Obszidián Öntőforma (Hűlő)', 'Obsidian Ingot Mold (Cooling)'),
    'obsidian_shovel': ('Obszidián Ásó', 'Obsidian Shovel'),
    'obsidian_slab_single': ('Obszidián Félblokk', 'Obsidian Slab'),
    'obsidian_stairs': ('Obszidián Lépcső', 'Obsidian Stairs'),
    'obsidian_tool_bench': ('Obszidián Szerszámpad', 'Obsidian Tool Bench'),
    'onion': ('Hagyma', 'Onion'),
    'onion_allium': ('Hagymás Virág (Allium)', 'Allium'),
    'orange': ('Narancs', 'Orange'),
    'orange_bed': ('Narancs Ágy', 'Orange Bed'),
    'orange_carpet': ('Narancs Szőnyeg', 'Orange Carpet'),
    'orange_dye': ('Narancs Festék', 'Orange Dye'),
    'orange_stained_clay_colored': ('Narancs Festett Agyag', 'Orange Stained Clay'),
    'orange_wool': ('Narancs Gyapjú', 'Orange Wool'),
    'orchid': ('Orchidea', 'Orchid'),
    'painting': ('Festmény', 'Painting'),
    'pink_bed': ('Rózsaszín Ágy', 'Pink Bed'),
    'pink_carpet': ('Rózsaszín Szőnyeg', 'Pink Carpet'),
    'pink_dye': ('Rózsaszín Festék', 'Pink Dye'),
    'pink_stained_clay_colored': ('Rózsaszín Festett Agyag', 'Pink Stained Clay'),
    'pink_wool': ('Rózsaszín Gyapjú', 'Pink Wool'),
    'piston': ('Dugattyú', 'Piston'),
    'pitaya_leaves': ('Pitahaya Levelek', 'Pitaya Leaves'),
    'polished_andesite': ('Csiszolt Andezit', 'Polished Andesite'),
    'polished_diorite': ('Csiszolt Diorit', 'Polished Diorite'),
    'polished_granite': ('Csiszolt Gránit', 'Polished Granite'),
    'potato': ('Krumpli', 'Potato'),
    'potion_of_g_2_moisture': ('Nedvesség Bájital II', 'Potion of Moisture II'),
    'pressure_plate_stone': ('Kő Nyomólemez', 'Stone Pressure Plate'),
    'pressure_plate_wood': ('Fa Nyomólemez', 'Wood Pressure Plate'),
    'pumpkin': ('Tök', 'Pumpkin'),
    'pumpkin_pie': ('Tökpite', 'Pumpkin Pie'),
    'pumpkin_seeds': ('Tök Mag', 'Pumpkin Seeds'),
    'pumpkin_soup': ('Tökleves', 'Pumpkin Soup'),
    'purple_bed': ('Lila Ágy', 'Purple Bed'),
    'purple_carpet': ('Lila Szőnyeg', 'Purple Carpet'),
    'purple_dye': ('Lila Festék', 'Purple Dye'),
    'purple_stained_clay_colored': ('Lila Festett Agyag', 'Purple Stained Clay'),
    'purple_wool': ('Lila Gyapjú', 'Purple Wool'),
    'quartz': ('Kvarc', 'Quartz'),
    'quartz_block': ('Kvarc Blokk', 'Quartz Block'),
    'quartz_pillar': ('Kvarc Pillér', 'Quartz Pillar'),
    'quartz_shard': ('Kvarc Szilánk', 'Quartz Shard'),
    'quartz_slab_single': ('Kvarc Félblokk', 'Quartz Slab'),
    'quartz_stairs': ('Kvarc Lépcső', 'Quartz Stairs'),
    'quiver': ('Nyíltegez', 'Quiver'),
    'rain_hat': ('Eső Kalap', 'Rain Hat'),
    'raw_fish_large': ('Nagy Nyers Hal', 'Large Raw Fish'),
    'recall_scroll': ('Visszahívó Tekercs', 'Recall Scroll'),
    'red_bed': ('Piros Ágy', 'Red Bed'),
    'red_carpet': ('Piros Szőnyeg', 'Red Carpet'),
    'red_slime_ball': ('Piros Nyálkagömb', 'Red Slime Ball'),
    'red_stained_clay_colored': ('Piros Festett Agyag', 'Red Stained Clay'),
    'red_wool': ('Piros Gyapjú', 'Red Wool'),
    'redstone_comparator': ('Redstone Komparátor', 'Redstone Comparator'),
    'redstone_lamp_unlit': ('Redstone Lámpa (Kialvadt)', 'Redstone Lamp (Unlit)'),
    'redstone_repeater': ('Redstone Ismétlő', 'Redstone Repeater'),
    'redstone_torch_lit': ('Redstone Fáklya', 'Redstone Torch'),
    'reinforced_eye_of_ender': ('Erősített Ender Szem', 'Reinforced Eye of Ender'),
    'reinforced_eye_of_ender_knowledge_book': ('Erősített Ender Szem Tudáskönyv', 'Reinforced Eye of Ender Knowledge Book'),
    'rose': ('Rózsa', 'Rose'),
    'rose_red': ('Rózsapiros Festék', 'Rose Red Dye'),
    'rotten_flesh': ('Rothadt Hús', 'Rotten Flesh'),
    'runestone_nul_adamantium': ('Adamantium Null Rúnakő', 'Adamantium Null Runestone'),
    'runestone_nul_mithril': ('Mithril Null Rúnakő', 'Mithril Null Runestone'),
    'rusted_iron_chain': ('Rozsdás Vas Lánc', 'Rusted Iron Chain'),
    'rusted_iron_chain_boots': ('Rozsdás Vas Lánc Csizma', 'Rusted Iron Chain Boots'),
    'rusted_iron_chain_chestplate': ('Rozsdás Vas Lánc Mellvért', 'Rusted Iron Chain Chestplate'),
    'rusted_iron_chain_helmet': ('Rozsdás Vas Lánc Sisak', 'Rusted Iron Chain Helmet'),
    'rusted_iron_chain_leggings': ('Rozsdás Vas Lánc Lábvért', 'Rusted Iron Chain Leggings'),
    'rusted_iron_short_sword': ('Rozsdás Vas Rövid Kard', 'Rusted Iron Short Sword'),
    'rusted_iron_war_hammer': ('Rozsdás Vas Háborús Kalapács', 'Rusted Iron War Hammer'),
    'sacred_sandstone': ('Szent Homokkő', 'Sacred Sandstone'),
    'saddle': ('Nyereg', 'Saddle'),
    'salad': ('Saláta', 'Salad'),
    'sandstone': ('Homokkő', 'Sandstone'),
    'sandstone_furnace_idle': ('Homokkő Kemence', 'Sandstone Furnace'),
    'sandstone_portal_stone': ('Homokkő Portálkő', 'Sandstone Portal Stone'),
    'sandstone_slab_single': ('Homokkő Félblokk', 'Sandstone Slab'),
    'sandstone_stairs': ('Homokkő Lépcső', 'Sandstone Stairs'),
    'sharp_flint_spear': ('Éles Kova Lándzsa', 'Sharp Flint Spear'),
    'sign': ('Tábla', 'Sign'),
    'silver_copper_war_hammer': ('Ezüst-Réz Háborús Kalapács', 'Silver-Copper War Hammer'),
    'simple_black_sleeping_bag': ('Fekete Hálózsák', 'Black Sleeping Bag'),
    'simple_blue_sleeping_bag': ('Kék Hálózsák', 'Blue Sleeping Bag'),
    'simple_bone_club': ('Egyszerű Csontbuzogány', 'Simple Bone Club'),
    'simple_brown_sleeping_bag': ('Barna Hálózsák', 'Brown Sleeping Bag'),
    'simple_cyan_sleeping_bag': ('Cián Hálózsák', 'Cyan Sleeping Bag'),
    'simple_flint_knife': ('Egyszerű Kova Kés', 'Simple Flint Knife'),
    'simple_gray_sleeping_bag': ('Szürke Hálózsák', 'Gray Sleeping Bag'),
    'simple_green_sleeping_bag': ('Zöld Hálózsák', 'Green Sleeping Bag'),
    'simple_light_blue_sleeping_bag': ('Világoskék Hálózsák', 'Light Blue Sleeping Bag'),
    'simple_light_gray_sleeping_bag': ('Világosszürke Hálózsák', 'Light Gray Sleeping Bag'),
    'simple_lime_sleeping_bag': ('Zöldessárga Hálózsák', 'Lime Sleeping Bag'),
    'simple_magenta_sleeping_bag': ('Magenta Hálózsák', 'Magenta Sleeping Bag'),
    'simple_orange_sleeping_bag': ('Narancs Hálózsák', 'Orange Sleeping Bag'),
    'simple_pink_sleeping_bag': ('Rózsaszín Hálózsák', 'Pink Sleeping Bag'),
    'simple_purple_sleeping_bag': ('Lila Hálózsák', 'Purple Sleeping Bag'),
    'simple_red_sleeping_bag': ('Piros Hálózsák', 'Red Sleeping Bag'),
    'simple_white_sleeping_bag': ('Fehér Hálózsák', 'White Sleeping Bag'),
    'simple_yellow_sleeping_bag': ('Sárga Hálózsák', 'Yellow Sleeping Bag'),
    'skin_care_bottle': ('Bőrápoló Üveg', 'Skin Care Bottle'),
    'slimeball_black': ('Fekete Nyálkagömb', 'Black Slime Ball'),
    'slimeball_brown': ('Barna Nyálkagömb', 'Brown Slime Ball'),
    'slimeball_gray': ('Szürke Nyálkagömb', 'Gray Slime Ball'),
    'slimeball_green': ('Zöld Nyálkagömb', 'Green Slime Ball'),
    'small': ('Kis Tárgy', 'Small Item'),
    'small_wooden_club': ('Kis Fa Buzogány', 'Small Wooden Club'),
    'smelting_furnace_idle': ('Olvasztó Kemence', 'Smelting Furnace'),
    'smooth_sandstone': ('Sima Homokkő', 'Smooth Sandstone'),
    'snow_block': ('Hóblokk', 'Snow Block'),
    'snow_slab': ('Hó Félblokk', 'Snow Slab'),
    'snow_thin': ('Hóréteg', 'Snow Layer'),
    'snowball': ('Hógolyó', 'Snowball'),
    'spruce_door': ('Fenyő Ajtó', 'Spruce Door'),
    'spruce_fence': ('Fenyő Kerítés', 'Spruce Fence'),
    'spruce_fence_gate': ('Fenyő Kerítés Kapu', 'Spruce Fence Gate'),
    'spruce_leaves': ('Fenyő Levelek', 'Spruce Leaves'),
    'spruce_sieve': ('Fenyő Szita', 'Spruce Sieve'),
    'spruce_wood_crate': ('Fenyő Fa Láda', 'Spruce Wood Crate'),
    'spruce_wood_slab_single': ('Fenyő Fa Félblokk', 'Spruce Wood Slab'),
    'spruce_wood_stairs': ('Fenyő Fa Lépcső', 'Spruce Wood Stairs'),
    'sticky_piston': ('Ragadós Dugattyú', 'Sticky Piston'),
    'stone': ('Kő', 'Stone'),
    'stone_brick_slab_single': ('Kőtégla Félblokk', 'Stone Brick Slab'),
    'stone_brick_stairs': ('Kőtégla Lépcső', 'Stone Brick Stairs'),
    'stone_bricks': ('Kőtéglák', 'Stone Bricks'),
    'stone_chip': ('Kőforgács', 'Stone Chip'),
    'stone_furnace_core': ('Kő Kemence Mag', 'Stone Furnace Core'),
    'stone_furnace_idle': ('Kő Kemence', 'Stone Furnace'),
    'stone_portal_stone': ('Kő Portálkő', 'Stone Portal Stone'),
    'stone_slab_single': ('Kő Félblokk', 'Stone Slab'),
    'stone_stairs': ('Kő Lépcső', 'Stone Stairs'),
    'string_sieve_mesh': ('Zsineg Szita Háló', 'String Sieve Mesh'),
    'sugar_block': ('Cukor Blokk', 'Sugar Block'),
    'sugar_cane': ('Cukornád', 'Sugar Cane'),
    'sugar_water': ('Cukros Víz', 'Sugar Water'),
    'teleport_scroll_knowledge_book': ('Teleport Tekercs Tudáskönyv', 'Teleport Scroll Knowledge Book'),
    'tnt': ('TNT', 'TNT'),
    'trapdoor': ('Csapóajtó', 'Trapdoor'),
    'trapped_chest': ('Csapdás Láda', 'Trapped Chest'),
    'tripwire_hook': ('Tripdrót Kampó', 'Tripwire Hook'),
    'tulip': ('Tulipán', 'Tulip'),
    'vegetable_soup': ('Zöldségleves', 'Vegetable Soup'),
    'villager_s_bed': ('Falusi Ágy', "Villager's Bed"),
    'vines': ('Kúszóka', 'Vines'),
    'water_bowl': ('Vizes Tál', 'Water Bowl'),
    'water_filter': ('Vízszűrő', 'Water Filter'),
    'water_skin': ('Víztömlő', 'Water Skin'),
    'waystone': ('Útjelzőkő', 'Waystone'),
    'waystone_knowledge_book': ('Útjelzőkő Tudáskönyv', 'Waystone Knowledge Book'),
    'weighted_pressure_plate_heavy': ('Nehéz Súlyozott Nyomólemez', 'Heavy Weighted Pressure Plate'),
    'weighted_pressure_plate_light': ('Könnyű Súlyozott Nyomólemez', 'Light Weighted Pressure Plate'),
    'wheat_seeds': ('Búza Mag', 'Wheat Seeds'),
    'wheat_soup': ('Búzaleves', 'Wheat Soup'),
    'white_stained_clay_colored': ('Fehér Festett Agyag', 'White Stained Clay'),
    'white_wool_portal_stone': ('Fehér Gyapjú Portálkő', 'White Wool Portal Stone'),
    'wither_skeleton_skull': ('Wither Csontváz Koponya', 'Wither Skeleton Skull'),
    'wither_skeleton_skull_fragment': ('Wither Csontváz Koponya Töredék', 'Wither Skeleton Skull Fragment'),
    'wood_slab_single': ('Fa Félblokk', 'Wood Slab'),
    'wooden_club': ('Fa Buzogány', 'Wooden Club'),
    'wooden_door': ('Fa Ajtó', 'Wooden Door'),
    'wooden_shovel': ('Fa Ásó', 'Wooden Shovel'),
    'wool_black': ('Fekete Gyapjú', 'Black Wool'),
    'wool_blue': ('Kék Gyapjú', 'Blue Wool'),
    'wool_brown': ('Barna Gyapjú', 'Brown Wool'),
    'wool_cyan': ('Cián Gyapjú', 'Cyan Wool'),
    'wool_gray': ('Szürke Gyapjú', 'Gray Wool'),
    'wool_green': ('Zöld Gyapjú', 'Green Wool'),
    'wool_light_blue': ('Világoskék Gyapjú', 'Light Blue Wool'),
    'wool_light_gray': ('Világosszürke Gyapjú', 'Light Gray Wool'),
    'wool_lime': ('Zöldessárga Gyapjú', 'Lime Wool'),
    'wool_magenta': ('Magenta Gyapjú', 'Magenta Wool'),
    'wool_orange': ('Narancs Gyapjú', 'Orange Wool'),
    'wool_pink': ('Rózsaszín Gyapjú', 'Pink Wool'),
    'wool_purple': ('Lila Gyapjú', 'Purple Wool'),
    'wool_red': ('Piros Gyapjú', 'Red Wool'),
    'wool_white': ('Fehér Gyapjú', 'White Wool'),
    'wool_yellow': ('Sárga Gyapjú', 'Yellow Wool'),
    'world_marker': ('Világ Jelölő', 'World Marker'),
    'world_marker_knowledge_book': ('Világ Jelölő Tudáskönyv', 'World Marker Knowledge Book'),
    'yellow_bed': ('Sárga Ágy', 'Yellow Bed'),
    'yellow_carpet': ('Sárga Szőnyeg', 'Yellow Carpet'),
    'yellow_stained_clay_colored': ('Sárga Festett Agyag', 'Yellow Stained Clay'),
    'yellow_wool': ('Sárga Gyapjú', 'Yellow Wool'),
}


def auto_translate(key):
    """Try pattern-based material+type translation."""
    materials = ['adamantium', 'ancient_metal', 'high_carbon_steel', 'hard_stone',
                 'rusted_iron', 'silver_copper', 'hardstone', 'obsidian',
                 'copper', 'silver', 'gold', 'iron', 'mithril', 'bronze', 'flint', 'quartz',
                 'oak', 'birch', 'spruce', 'jungle']
    for mat in materials:
        if key.startswith(mat + '_'):
            suffix = key[len(mat)+1:]
            if suffix in TYPE_HU and suffix in TYPE_EN:
                mat_hu = MAT_HU.get(mat, mat)
                mat_en = MAT_EN.get(mat, mat)
                return (f'{mat_hu} {TYPE_HU[suffix]}', f'{mat_en} {TYPE_EN[suffix]}')
    return None


with open('data/items.json', encoding='utf-8') as f:
    items = json.load(f)

changes = 0
missing = []
for key, val in items.items():
    hu = val.get('name', {}).get('hu', '')
    en = val.get('name', {}).get('en', '')
    if hu != key and en != key and hu != '' and en != '':
        continue  # already translated

    if key in MANUAL:
        items[key]['name']['hu'] = MANUAL[key][0]
        items[key]['name']['en'] = MANUAL[key][1]
        changes += 1
    else:
        auto = auto_translate(key)
        if auto:
            items[key]['name']['hu'] = auto[0]
            items[key]['name']['en'] = auto[1]
            changes += 1
        else:
            missing.append(key)

print(f'Translated: {changes}')
print(f'Still missing: {len(missing)}')
for m in missing:
    print(f'  MISSING: {m}')

with open('data/items.json', 'w', encoding='utf-8') as f:
    json.dump(items, f, ensure_ascii=False, indent=2)
print('Saved.')
